nginx:
  image: nginx
  volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - /www/web:/usr/share/nginx/html
  ports:
    - "8080:80"
  links:
    - php:php

php:
  image: php:7.2-fpm
  expose:
    - "9000"
  links:
    - mysql
    - redis
  volumes:
    - /www/web:/usr/share/nginx/html

redis:
  image: redis
  ports:
    - "6379:6379"
  volumes:
    - /data/redis:/data
  command: redis-server --appendonly yes

mysql:
  image: mysql:dev2
  ports:
    - "3306:3306"
  volumes:
    - /data/mysql:/var/lib/mysql
  env_file:
    - .env 
